gatsby-uc/plugins

- packages/gatsby-plugin-github-ribbon/README.md
> feat(github-ribbon): docs update and release other changes

- .github/workflows/prettier.yml
> chore: update prettier run

- .github/workflows/prettier.yml
> TEST: prettier skip

- .github/workflows/prettier.yml
- .github/workflows/release.yml
there's a cache built in t the node-setup action so I'm trying that to simplify configs
> chore(actions): simplify caching setup

- .github/CODEOWNERS
- CONTRIBUTING.md
adds code owners file to notify particular groups or people when files are being changed. Treating this as an experiment. we'll see how it goes. 
added to contributing docs.
> chore(repo): add code owners

- .changeset/clever-rivers-hide.md
- packages/gatsby-plugin-vanilla-extract/README.md
We've added the example to our repo, so just updating the TODO here
> chore(gatsby-plugin-vanilla-extract): Update README

- .changeset/proud-pears-marry.md
- packages/gatsby-plugin-fastify/README.md
Just fixes a couple broken documentation links & a typo.
> Updated broken fastify documentation links & fixed typo

- .changeset/gold-impalas-hunt.md
- .changeset/weak-files-beg.md
- packages/gatsby-plugin-github-ribbon/jest.config.js
> fix: work around for jest on broken tests

- .changeset/moody-plums-sniff.md
- packages/gatsby-plugin-fastify/README.md
- packages/gatsby-plugin-fastify/package.json
- packages/gatsby-plugin-fastify/src/plugins/404.ts
- packages/gatsby-plugin-fastify/src/plugins/500.ts
- packages/gatsby-plugin-fastify/src/plugins/clientRoutes.ts
- packages/gatsby-plugin-fastify/src/plugins/decorators.ts
- packages/gatsby-plugin-fastify/src/plugins/functions.ts
- packages/gatsby-plugin-fastify/src/plugins/gatsby.ts
- packages/gatsby-plugin-fastify/src/plugins/redirects.ts
- packages/gatsby-plugin-fastify/src/plugins/serverRoutes.ts
- packages/gatsby-plugin-fastify/src/plugins/static.ts
- packages/gatsby-plugin-fastify/src/utils/headers.ts
- yarn.lock
Implementing some better handling of the `x-gatsby-fastify` header for future improvements. 
Undocumented internal fastify plugin as I don't want to support these. If we decide to the gatsby fastify plugin should probably be published as it's on plugin. 
Needed for #199 and others
> refactor(gatsby-pluginfastify): misc

- .changeset/thin-cougars-knock.md
- integration-tests/plugin-fastify/benchmark.js
- integration-tests/plugin-fastify/package.json
- packages/gatsby-plugin-fastify/README.md
- packages/gatsby-plugin-fastify/package.json
- packages/gatsby-plugin-fastify/src/__tests__/__files__/public/posts/page-1/index.html
- packages/gatsby-plugin-fastify/src/__tests__/__utils__/config.js
- packages/gatsby-plugin-fastify/src/__tests__/plugins/gatsby.js
- packages/gatsby-plugin-fastify/src/plugins/clientRoutes.ts
- packages/gatsby-plugin-fastify/src/plugins/gatsby.ts
- packages/gatsby-plugin-fastify/src/plugins/reverseProxy.ts
- packages/gatsby-plugin-fastify/src/plugins/static.ts
- packages/gatsby-plugin-fastify/src/serve.ts
- yarn.lock
update deps and code to support fastify v4
Done.
None
> chore(gatsby-plugin-fastify): fastify v4 and related updates

- .changeset/slow-cycles-dance.md
- packages/gatsby-source-s3/src/gatsby-node.ts
Error handling changes and improved schema definition for Gatsby are intended to resolve #255. Or at least surface the correct error and not throw the erroneous schema errors related to invalid queries. 
#255
> refactor(gatsby-plugin-s3): Simplify Types and improve error handling

- yarn.lock
> update caniuse lite

- .changeset/green-cooks-rest.md
- packages/gatsby-plugin-fastify/README.md
Fixes Typo in fastify server docs
fixed!
closes #265
> docs(gatsby-plugin-fastify): fixes docs typo

- .changeset/violet-bags-pretend.md
- .prettierignore
- packages/gatsby-plugin-fastify/README.md
- packages/gatsby-plugin-fastify/package.json
- packages/gatsby-plugin-fastify/src/__tests__/__utils__/config.js
- packages/gatsby-plugin-fastify/src/cli.ts
- packages/gatsby-plugin-fastify/src/gatsby-node.ts
- packages/gatsby-plugin-fastify/src/serve.ts
- packages/gatsby-plugin-fastify/src/utils/config.ts
- scripts/gatsby-export-test.mjs
- yarn.lock
Allow passing Fastify options from Gatsby plugin options,
Docs have been updated!
closes #268
> feat(gatsby-plugin-fastify): Fastify Options

- .changeset/violet-bags-pretend.md
- integration-tests/plugin-fastify/package.json
- packages/gatsby-plugin-fastify/README.md
- packages/gatsby-plugin-fastify/src/__tests__/__utils__/config.js
- packages/gatsby-plugin-fastify/src/__tests__/utils/routes.ts
- packages/gatsby-plugin-fastify/src/plugins/decorators.ts
- packages/gatsby-plugin-fastify/src/plugins/gatsby.ts
- packages/gatsby-plugin-fastify/src/serve.ts
- packages/gatsby-plugin-fastify/src/utils/server.ts
Fixing bugs, issues found with #321
> refactor(gatsby-plugin-fastify): Fixes found in pre-release

- .changeset/red-pants-tan.md
- integration-tests/plugin-fastify/gatsby-node.ts
- packages/gatsby-plugin-fastify/src/__tests__/plugins/redirects.js
- packages/gatsby-plugin-fastify/src/plugins/redirects.ts
- packages/gatsby-plugin-fastify/src/utils/routes.ts
fixes DoS vulnerability in https://github.com/gatsby-uc/plugins/issues/327
closes https://github.com/gatsby-uc/plugins/issues/327
> fix(gatsby-plugin-fastify): encode replacements in wildcard redirects

- .changeset/light-garlics-smile.md
- .changeset/loud-points-decide.md
> fix: missing cs

- .changeset/spotty-buses-cheer.md
- packages/gatsby-source-strapi/README.md
With localhost, you get this error: `Error: connect ECONNREFUSED ::1:1337`
See also https://stackoverflow.com/a/74556840
> Update Strapi README

- .changeset/poor-parents-deny.md
- packages/gatsby-source-strapi/package.json
- yarn.lock
> Revert "fix(packages): update dependency axios to v1"

- .changeset/few-points-do.md
- packages/gatsby-source-strapi/src/fetch.js
> fix(gatsby-soure-strapi): No need for JSON.stringify when results are already String

- .changeset/thick-eggs-admire.md
- eslint.config.js
- packages/gatsby-source-strapi/README.md
- packages/gatsby-source-strapi/src/axios-instance.js
- packages/gatsby-source-strapi/src/clean-data.js
- packages/gatsby-source-strapi/src/fetch.js
- packages/gatsby-source-strapi/src/gatsby-node.js
- packages/gatsby-source-strapi/src/helpers.js
- packages/gatsby-source-strapi/src/normalize.js
support the new REST API of Strapi 5 and use the `documentId`
> support strapi 5

- packages/gatsby-plugin-github-ribbon/package.json
- packages/gatsby-plugin-pinterest/package.json
- packages/gatsby-plugin-relative-ci/package.json
- packages/gatsby-source-packagist/package.json
- packages/gatsby-source-s3/package.json
- packages/gatsby-source-strapi/package.json
- yarn.lock
> Revert "fix(packages): update non-major dependency versions"
